# permissions for end users to edit scalars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scalar-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sampleoperator
    app.kubernetes.io/part-of: sampleoperator
    app.kubernetes.io/managed-by: kustomize
  name: scalar-editor-role
rules:
- apiGroups:
  - api.phanindhra.reddy
  resources:
  - scalars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.phanindhra.reddy
  resources:
  - scalars/status
  verbs:
  - get
