---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.phanindhra.reddy
  resources:
  - fenodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.phanindhra.reddy
  resources:
  - fenodes/finalizers
  verbs:
  - update
- apiGroups:
  - api.phanindhra.reddy
  resources:
  - fenodes/status
  verbs:
  - get
  - patch
  - update
