apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: fenodeoperator-system  # Update with your namespace if needed
spec:
  selector:
    control-plane: controller-manager
  ports:
    - protocol: TCP
      port: 8020
      targetPort: 8020
